services:
  postgres_test:
    image: postgres:16-alpine
    container_name: users_api_postgres_test
    ports:
      - '${DATABASE_PORT:?DATABASE_PORT is required}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:?DATABASE_USER is required}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD is required}
      POSTGRES_DB: ${DATABASE_NAME:?DATABASE_NAME is required}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_test_data:
